### PR TITLE
Reduced complexity and proper use of the ca cache

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by aik099** [comment]
Any reason why static method variable was replaced with static class property?

**Comment by Nyholm** [comment]
Yes. See here: https://github.com/padraic/file_get_contents/blob/master/src/Humbug/FileGetContents.php#L294-L297

``` php
        static $found = null;
        if ($found !== null) {
            return $found;
        }
```

This if statement will never evaluate to true.

**Comment by aik099** [comment]
Ah, static variable within static method. You're right. Thanks for noticing.

There is another PR (see #9), that is changing same code, but it removes all of it to use external library for detecting certificate.

**Comment by Nyholm** [comment]
I really like this library but it could be more SOLID and some code clean up. I made this small PR to see how open the maintainers are for changes. 

I would like to see #9 to get merged. Im happy to close this PR in favor for #9

**Comment by aik099** [comment]
This library is good for people using `file_get_contents`. I personally prefer to disable `allow_url_fopen` setting in `php.ini` and explicitly use CURL for getting contents from remote websites. This is more explicit and don't have any security implications as it was with `file_get_contents` function.

**Comment by Nyholm** [comment]
Yes, I very much agree

**Review by theofidry — APPROVED** [review]
Seems good to me, glad to see you there as well @Nyholm ;)

@padraic the PR looks good to me but #9 seems to be a nice replacement

**Comment by Nyholm** [comment]
Thank you @theofidry. Im happy that you got write access here. =)

**Review by padraic — APPROVED** [review]

**Comment by theofidry** [comment]
Closed via #9

**Pull request closed without merging**
